spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cross-shoes
    username: cross-shoes-admin
    password: cross-shoes-admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true